export enum ReportReason {
  SPAM = 'SPAM',
  COMPORTAMIENTO_INAPROPIADO = 'COMPORTAMIENTO_INAPROPIADO',
  CONTENIDO_OFENSIVO = 'CONTENIDO_OFENSIVO',
  ACOSO = 'ACOSO',
  FRAUD = 'FRAUD',
  INFORMACION_FALSA = 'INFORMACION_FALSA',
  OTRO = 'OTRO',
}

export enum ReportType {
  USER = 'USER',
  CONTENT = 'CONTENT',
}