sonar.projectKey=The-Johnnie-Walkers_peerly-reports-management
sonar.organization=the-johnnie-walkers
sonar.projectName=Backend Reports
sonar.sources=src
sonar.exclusions=**/*.spec.ts,**/node_modules/**,**/dist/**,**/coverage/**
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info
